sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_4934eb8c937d_key -iv $encrypted_4934eb8c937d_iv -in multi-k8s-355314-fa53c51cd4dc.json.enc -out multi-k8s-355314-fa53c51cd4dc.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
