sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_4934eb8c937d_key -iv $encrypted_4934eb8c937d_iv -in multi-k8s-355314-fa53c51cd4dc.json.enc -out multi-k8s-355314-fa53c51cd4dc.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-355314-fa53c51cd4dc.json
  - gcloud config set project multi-k8s-355314
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dita/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dita/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
